{{- if .Values.immich.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: immich
  annotations:
    kubernetes.io/ingress.class: {{ .Values.immich.ingress.className }}
    cert-manager.io/cluster-issuer: {{ .Values.immich.ingress.annotations."cert-manager.io/cluster-issuer" }}
spec:
  tls:
    - hosts:
        - {{ (index .Values.immich.ingress.hosts 0).host }}
      secretName: {{ (index .Values.immich.ingress.tls 0).secretName }}
  rules:
    - host: {{ (index .Values.immich.ingress.hosts 0).host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: immich
                port:
                  number: 80
{{- end }}