apiVersion: v1
kind: Secret
metadata:
  name: immich-postgres-user
type: Opaque
stringData:
  username: {{ .Values.postgres.username | default "" | quote }}
  password: {{ .Values.postgres.password | default "" | quote }}