apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-postgres-user
  namespace: immich-staging
spec:
  encryptedData:
    username: Ag... # sealed
    password: Ag... # sealed
  template:
    metadata:
      name: immich-postgres-user
      namespace: immich-staging
    type: Opaque